version: '3'
  
networks:
  default:
    driver: bridge

services:
  db:
    networks:
      - default
    image: mysql:5.7
    ports:
      - 3336:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./database:/var/lib/mysql"
  app:
    image: registry.handh.ru/location/backend-app:latest
    restart: always
    ports:
      - "8877:8877"
    networks:
      - default
    depends_on:
      - db    
    environment:
      MYSQL_HOST: "db:3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "hh-location"


